version: '3.0'
services:
  dev:
    image: node
    user: $UID:$GID
    volumes:
    - .:/code
    entrypoint:
    - /usr//bin/tail
    - -f
    - /etc/hosts

  build:
    image: node
    user: $UID:$GID
    working_dir: /code
    volumes:
    - .:/code
    entrypoint:
    - make

  run:
    build: .
    ports:
    - "8000:8000"
    user: $UID:$GID
